SELECT Reservation_ID, Customer_ID, Branch_ID, ClassID, PICK_UP_D, DROP_OFF_D, CC_No 
FROM RESERVATION 
WHERE Customer_ID IN ( 
    SELECT Customer_ID 
    FROM RESERVATION 
    GROUP BY Customer_ID 
    HAVING COUNT(*) > 1 
); 
 

SELECT COLUMN_NAME 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'RESERVATION'; 